name: Resolve File Includes
author: Daniel Cazzulino
description: "Resolves include directives written as HTML comments, like <!-- include: path/to/file.md --> (i.e. in your readme)"

inputs:
  include:  # files to include for processing
    description: 'Used as the Get-ChildItem -Include parameter, i.e. *.md'
    required: false
    default: '*.md'
  exclude:  # files to exclude from processing
    description: 'Used as the Get-ChildItem -Exclude parameter, foo.md'
    required: false
    default: ''
  recurse:  # whether to recurse into subdirectories
    description: 'Whether to process files recursively in subdirectories' 
    required: false
    default: true
  validate: 
    description: 'Whether to validate (and error) include links' 
    required: false
    default: true

branding:
  icon: "code"
  color: "purple"

runs:
  using: "composite"
  steps:
    - name: includes
      shell: pwsh
      run: |
        &"$env:GITHUB_ACTION_PATH/resolve-file-includes.ps1"
      env:
        RESOLVE_INCLUDE: ${{ inputs.include }}
        RESOLVE_EXCLUDE: ${{ inputs.exclude }}
        RESOLVE_RECURSE: ${{ inputs.recurse }}
        RESOLVE_VALIDATE: ${{ inputs.validate }}